### ISSUE TITLE
Committer of Changes to Pending Trigger File Should Be Configurable

### ISSUE THREAD

**Issue by davewalter** [cfmobile/pool-trigger#2]
The Release Engineering team has noticed several commits to our concourse environment pool by the "pcf-toronto-ci-bot" github user. This really should be configurable so that we could use our own CI bot user.

**Comment by danger-ranger** [comment]
Story Added: https://www.pivotaltracker.com/story/show/109273708

**Comment by danger-ranger** [comment]
rather than make it configurable we just followed the precedent of the pool-resource and made it use a fake CI Pool Trigger Resource user
